FROM scratch

MAINTAINER Black Duck OpsSight Team

ARG LASTCOMMIT
ARG BUILDTIME

# Container catalog requirements
COPY ./../LICENSE /licenses/
COPY ./pod-controller-help.1 /help.1

COPY ./_output/pod-perceiver ./pod-perceiver

LABEL name="Black Duck OpsSight Pod Controller" \
      vendor="Black Duck Software" \
      release.version="1.0" \
      summary="Black Duck OpsSight Pod Controller" \
      description="This container is used to identify all images inside each pod in any Kubernetes or Red Hat OpenShift cluster. It should send all those identified images to opssight-core to scan them. It should also retrieve the vulnerability and policy violations of each image periodically from opssight-core scan results and annotate and label them in all pods." \
      lastcommit="$LASTCOMMIT" \
      buildtime="$BUILDTIME"

CMD ["./pod-perceiver"]
