.TH NAME
.PP
opssight-image-controller


.SH DESCRIPTION
.PP
The opssight-image-controller is used to identify all images in Red Hat OpenShift cluster. It should send all those identified images to opssight-core to scan them. It should also retrieve the vulnerability and policy violations of each image periodically from opssight-core scan results and annotate and label them in all images.


.SH USAGE
.PP
The opssight-image-controller will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
The opssight-image-controller requires admin access which are fully documented in the OpsSight for Red Hat OpenShift security document.


.SH AUTHORS
.PP
Black Duck Software
