# Default values for bd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

isKubernetes: true

imageTag: 2.2.5

# Docker registry to pull Black Duck images
registry: docker.io/blackducksoftware
