.TH NAME
.PP
opssight-scanner


.SH DESCRIPTION
.PP
The opssight-scanner is used to scan images received from opsight-core. It calls the Black Duck scan client.


.SH USAGE
.PP
We recommend running the opsight-scanner only in the context of an OpsSight Connector solution.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
There are no security implications of running opssight-scanner in OpenShift environment.


.SH AUTHORS
.PP
Black Duck Software
