.TH NAME
.PP
opsight-image-getter


.SH DESCRIPTION
.PP
The opsight-image-getter is used to retrieve images that need to be scanned.


.SH USAGE
.PP
We recommend running the opsight-image-getter only in the context of an OpsSight Connector solution.

.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
The opsight-image-getter requires elevated privileges. For more information, see the OpsSight for Red Hat OpenShift Security Disclosures document.


.SH AUTHORS
.PP
Black Duck Software
