.TH NAME
.PP
opsight-image-getter


.SH DESCRIPTION
.PP
The opsight-image-getter is used to get images from Docker and save them as tar ball.


.SH USAGE
.PP
The opsight-image-getter will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.

.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
The opsight-image-getter requires elevated privileges. For more information, see the OpsSight for Red Hat OpenShift Security Disclosures document.


.SH AUTHORS
.PP
Black Duck Software
