.TH NAME
.PP
opssight-scanner


.SH DESCRIPTION
.PP
The opssight-scanner is used to scan the images that is received from opsight-core. It should call the blackduck scanner client to scan those images.


.SH USAGE
.PP
The opssight-scanner will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
There is no security implications for opssight-scanner in OpenShift environment


.SH AUTHORS
.PP
Black Duck Software
