.TH NAME
.PP
opsight-image-puller


.SH DESCRIPTION
.PP
The opsight-image-puller is used to pull the images from docker and save them as TAR ball.


.SH USAGE
.PP
The opsight-image-puller will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.

.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
The opsight-image-puller requires elevated privileges which are fully documented in the OpsSight for Red Hat OpenShift security document.


.SH AUTHORS
.PP
Black Duck Software
