.TH NAME
.PP
opssight-core


.SH DESCRIPTION
.PP
The opssight-core is used to get images from opsight-image-processor and opssight-pod-processor in Kubernetes or Red Hat OpenShift clusters. It will send received images to the Black Duck scanner for scanning. It will also retrieve vulnerability and policy violations for each image periodically from the Black Duck Hub and update the scan results.


.SH USAGE
.PP
We recommend running the opsight-core only in the context of an OpsSight Connector solution.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
There are no security implications of running opssight-core in OpenShift environment.


.SH AUTHORS
.PP
Black Duck Software
