apiVersion: v1
data:
  {{ .Values.blackduck.connectionsEnvironmentVariableName }}: {{ include "ops.externalBlackDuck" . | b64enc }}
  securedRegistries.json: {{ include "ops.securedRegistries" . | b64enc }}
kind: Secret
metadata:
  labels:
    app: opssight
    component: blackduck
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-blackduck
  namespace: {{ .Release.Namespace }}
type: Opaque
