apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  data:
    pyfire.json: '{"PerceptorURL": "perceptor-ops.10.1.176.68.xip.io", "HubURL": "engsreepath471-engsreepath471.10.1.176.130.xip.io", "Port": 3101}'
  kind: ConfigMap
  metadata:
    name: pyfire
- apiVersion: v1
  kind: Service
  metadata:
    name: pyfire
  spec:
    ports:
    - port: 3101
      protocol: TCP
      targetPort: 3101
    selector:
      name: pyfire
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: pyfire
    name: pyfire
  spec:
    containers:
    - args:
      - run.py
      - /etc/pyfire/pyfire.json
      command:
      - python3
#      env:
#      - name: PCP_HUBUSERPASSWORD
#        valueFrom:
#          secretKeyRef:
#            key: HubUserPassword
#            name: blackduck-secret
#            optional: false
      image: docker.io/mikephammer/pyfire:latest
      imagePullPolicy: Always
      name: pyfire
      ports:
      - containerPort: 3101
        protocol: TCP
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
#      securityContext:
#        capabilities:
#          drop:
#          - KILL
#          - MKNOD
#          - SETGID
#          - SETUID
#        runAsUser: 1004690000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/pyfire
        name: pyfire
#      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#        name: default-token-dj9j7
#        readOnly: true
    restartPolicy: Always
    schedulerName: default-scheduler
#    securityContext:
#      fsGroup: 1004690000
#      seLinuxOptions:
#        level: s0:c68,c67
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - configMap:
        defaultMode: 420
        name: pyfire
      name: pyfire
#    - name: default-token-dj9j7
#      secret:
#        defaultMode: 420
#        secretName: default-token-dj9j7