.TH NAME
.PP
opssight-deployer


.SH DESCRIPTION
.PP
The opssight-deployer is used to deploy all the containers that is required for Blackduck OpsSight product.


.SH USAGE
.PP
The opssight-deployer will not perform meaningful work if launched outside of an OpenShift or Kubernetes environment or in a standalone fashion.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
Admin privileges is required to add roles to the service account which are fully documented in the OpsSight for Red Hat OpenShift security document.

.SH AUTHORS
.PP
Black Duck Software
