apiVersion: v1
kind: List
metadata:
  name: opssight-cloud-auth
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opssight-cloud-auth
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: opssight-cloud-auth
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - update
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: opssight-cloud-auth
  subjects:
  - kind: ServiceAccount
    name: opssight-cloud-auth
    namespace: kube-system
  roleRef:
    kind: Role
    name: opssight-cloud-auth
    apiGroup: ""
- apiVersion: v1
  kind: Secret
  metadata:
    name: opssight-cloud-auth
    namespace: kube-system
  data:
    application_default_credentials.json: "<<GCR_DEFAULT_CREDENTIAL_FILE>>"
    GCR_URL: "<<GCR_URL>>"
  type: Opaque
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: opssight-cloud-auth
    name: opssight-cloud-auth
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: opssight-cloud-auth
    template:
      metadata:
        labels:
          run: opssight-cloud-auth
      spec:
        containers:
        - env:
          - name: REFRESH_IN_MINUTES
            value: "60"
          - name: GCR_URL
            valueFrom:
              secretKeyRef:
                name: opssight-cloud-auth
                key: GCR_URL
          - name: NAME
            value: "<<OPSSIGHT_RELEASE_NAME>>"
          - name: NAMESPACE
            value: "<<OPSSIGHT_RELEASE_NAMESPACE>>"
          image: docker.io/blackducksoftware/opssight-cloud-auth:2.2.6-RC
          imagePullPolicy: Always
          name: opssight-cloud-auth
          command:
          - ./opssight-cloud-auth
          ports:
          - containerPort: 3001
            protocol: TCP
          volumeMounts:
          - name: gcr-creds
            mountPath: "/root/.config/gcloud"
            readOnly: true
        volumes:
        - name: gcr-creds
          secret:
            secretName: opssight-cloud-auth
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: opssight-cloud-auth
