apiVersion: v1
kind: List
metadata:
  name: opssight-cloud-auth
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opssight-cloud-auth
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: opssight-cloud-auth
  rules:
  - apiGroups:
    - synopsys.com
    resources:
    - opssights
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - update
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: opssight-cloud-auth
  subjects:
  - kind: ServiceAccount
    name: opssight-cloud-auth
    namespace: kube-system
  roleRef:
    kind: ClusterRole
    name: opssight-cloud-auth
    apiGroup: ""
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: opssight-cloud-auth
    name: opssight-cloud-auth
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: opssight-cloud-auth
    template:
      metadata:
        labels:
          run: opssight-cloud-auth
      spec:
        containers:
        - env:
          - name: AWS_ACCOUNT_IDS
            value: "<<AWS_ACCOUNT_ID>>"
          - name: REFRESH_IN_MINUTES
            value: "5"
          - name: AWS_ACCESS_KEY_ID
            value: "<<AWS_ACCESS_KEY_ID>>"
          - name: AWS_SECRET_ACCESS_KEY
            value: "<<AWS_SECRET_ACCESS_KEY>>"
          - name: GCR_URL
            value: "<<GCR_URL>>"
          image: docker.io/blackducksoftware/opssight-cloud-auth:2.2.2-RC
          imagePullPolicy: Always
          name: opssight-cloud-auth
          command:
          - ./opssight-cloud-auth
          ports:
          - containerPort: 3001
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: opssight-cloud-auth
