.TH NAME
.PP
opssight-artifactory-processor


.SH DESCRIPTION
.PP
The opssight-artifactory-processor is used to identify all Artifactory images in a Red Hat OpenShift cluster. It will send all the identified images to opssight-core for scanning. It will also retrieve vulnerability and policy violations for each image periodically from opssight-core and annotate and label the Artifactory image with the information.


.SH USAGE
.PP
The opssight-artifactory-processor will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
There are no security implications of running opssight-artifactory-processor in OpenShift environment.


.SH AUTHORS
.PP
Black Duck Software
