steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '-c',  '-o', './cmd/mirage', './basicskyfire/']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/opssight-connector/e2e'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/opssight-connector:$BRANCH_NAME', './cmd/.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/opssight-connector:$BRANCH_NAME']
