apiVersion: v1
kind: List
metadata:
  name: "Mirage Automation"
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: mirage
  spec:
    volumes:
      - name: mirage
        configMap:
          name: mirage
      - name: dir-docker-socket
        hostPath:
          path: /var/run/docker.sock
    containers:
      - name: mirage
        image: docker.io/msenmurugan/mirage:latest
        volumeMounts:
          - name: mirage
            mountPath: /etc/mirage
          - mountPath: /var/run/docker.sock
            name: dir-docker-socket
        imagePullPolicy: Always
        command:
          - "./mirage"
        args:
          - "--configPath"
          - "/etc/mirage/mirage.yaml"
        terminationMessagePath: /dev/termination-log
    restartPolicy: Never
    serviceAccountName: perceiver
    serviceAccount: perceiver
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mirage
  data:
    mirage.yaml: |
      DefaultCPU: "10m"
      DefaultMem: "64Mi"
      DryRun: false
      Namespace: "perceptor"
      SkyfireHost: "skyfire"
      SkyfirePort: "3005"
      NoOfPods: 30
      LogLevel: "info"
