apiVersion: v1
kind: Pod
metadata:
  name: mirage
spec:
#  volumes:
#  - name: viper-input
#    configMap:
#      name: viper-input
  containers:
    - name: mirage
      image: gcr.io/gke-verification/blackducksoftware/opssight-mirage:viper-input
      imagePullPolicy: Always
      command: ["./mirage"]
      args: ["--skyfireHost", "skyfire", "--skyfirePort", "3005"]
#      ports:
#     - containerPort: 3002
      terminationMessagePath: /dev/termination-log
  restartPolicy: Never
#  serviceAccountName: mirage-sa
#  serviceAccount: mirage-sa
