apiVersion: v1
kind: Pod
metadata:
  name: mirage
spec:
#  volumes:
#  - name: viper-input
#    configMap:
#      name: viper-input
  containers:
    - name: mirage
      image: gcr.io/gke-verification/blackducksoftware/opssight-mirage:e2e-stub
      imagePullPolicy: Always
      command: ["./mirage"]
      args: ["--skyfireBaseURL", "http://www.google.com"]
#      ports:
#     - containerPort: 3002
      terminationMessagePath: /dev/termination-log
  restartPolicy: Never
#  serviceAccountName: mirage-sa
#  serviceAccount: mirage-sa
