apiVersion: v1
data:
  opssight.json: |-
    {
      "Perceiver": {
        "Certificate": {{ .Values.spec.perceiver.certificate | quote }},
        "CertificateKey": {{ .Values.spec.perceiver.certificateKey | quote }},
        "AnnotationIntervalSeconds": {{ .Values.spec.perceiver.annotationIntervalSeconds }},
        "DumpIntervalMinutes": {{ .Values.spec.perceiver.dumpIntervalMinutes }},
        "Port": {{ .Values.spec.perceiver.port }},
        "Pod": {
          "NamespaceFilter": {{ .Values.spec.perceiver.podPerceiver.nameSpaceFilter | quote }}
        },
        "Artifactory": {
          "Dumper": {{ .Values.spec.perceiver.enableArtifactoryProcessorDumper }}
        }
      },
      "BlackDuck": {
        "ConnectionsEnvironmentVariableName": {{ .Values.spec.blackduck.connectionsEnvironmentVariableName | toString | quote }},
        "TLSVerification": {{ .Values.spec.blackduck.tlsVerification }}
      },
      "Perceptor": {
        "Timings": {
          "CheckForStalledScansPauseHours": {{ .Values.spec.perceptor.timings.checkForStalledScansPauseHours }},
          "StalledScanClientTimeoutHours": {{ .Values.spec.perceptor.timings.stalledScanClientTimeoutHours }},
          "ModelMetricsPauseSeconds": {{ .Values.spec.perceptor.timings.modelMetricsPauseSeconds }},
          "UnknownImagePauseMilliseconds": {{ .Values.spec.perceptor.timings.unknownImagePauseMilliseconds }},
          "ClientTimeoutMilliseconds": {{ .Values.spec.perceptor.timings.clientTimeoutMilliseconds }}
        },
        "UseMockMode": {{ .Values.spec.perceptor.useMockMode }},
        "Host": "{{ .Release.Name }}-opssight-core",
        "Port": {{ .Values.spec.perceptor.port }}
      },
      "Scanner": {
        "Port": {{ .Values.spec.scannerPod.scanner.port }},
        "ImageDirectory": {{ .Values.spec.scannerPod.scanner.imageDirectory  | toString | quote }},
        "BlackDuckClientTimeoutSeconds":  {{ .Values.spec.scannerPod.scanner.blackDuckClientTimeoutSeconds }}
      },
      "ImageFacade": {
        "Host": {{ .Values.spec.scannerPod.imageFacade.host  | toString | quote }},
        "Port": {{ .Values.spec.scannerPod.imageFacade.port }},
        "ImagePullerType": {{ .Values.spec.scannerPod.imageFacade.imagePullerType  | toString | quote }},
        "CreateImagesOnly": {{ .Values.spec.scannerPod.imageFacade.createImagesOnly }}
      },
      "LogLevel": {{ .Values.spec.logLevel | toString | quote }}
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: {{ .Release.Name }}-opssight-opssight
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-opssight
  namespace: {{ .Release.Namespace }}
