apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: core
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-core
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    app: opssight
    component: core
    name: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: core
        name: {{ .Release.Name }}
      name: {{ .Release.Name }}-opssight-core
    spec:
      containers:
      - args:
        - /etc/core/opssight.json
        command:
        - ./opssight-core
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-opssight-blackduck
        {{- if .Values.core.registry }}
          {{- if .Values.core.imageTag }}
        image: {{ .Values.core.registry }}/opssight-core:{{ .Values.core.imageTag }}
          {{- else }}
        image: {{ .Values.core.registry }}/opssight-core:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.core.imageTag }}
        image: {{ .Values.registry }}/opssight-core:{{ .Values.core.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/opssight-core:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        name: core
        ports:
        - containerPort: 3001
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.core.requestCpu }}
            memory: {{ .Values.core.requestMemory }}
        volumeMounts:
        - mountPath: /etc/core
          name: core
      dnsPolicy: ClusterFirst
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-opssight-opssight
        name: core
status:
  replicas: 0
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: core
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-core
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-core
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: opssight
    component: core
    name: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
