apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: prometheus
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app: opssight
      component: prometheus
      name: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: prometheus
        name: {{ .Release.Name }}
      name: {{ .Release.Name }}-opssight-prometheus
    spec:
      containers:
      - args:
        - --log.level=debug
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/tmp/data/
        - --storage.tsdb.retention=120d
        - --web.listen-address=:3006
        {{- if .Values.prometheus.registry }}
        image: {{ .Values.prometheus.registry }}/prometheus:{{ .Values.prometheus.imageTag }}
        {{- else }}
        image: {{ .Values.init.registry }}/prometheus:{{ .Values.init.imageTag }}
        {{- end}}
        name: prometheus
        ports:
        - containerPort: 3006
          name: web
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/prometheus
          name: prometheus
      dnsPolicy: ClusterFirst
      {{- include "ops.imagePullSecrets" . | nindent 6 }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-opssight-prometheus
        name: prometheus
      - emptyDir: {}
        name: data
status: {}
---
apiVersion: v1
data:
  prometheus.yml: '{"global":{"scrape_interval":"5s"},"scrape_configs":[{"job_name":"perceptor-scrape","scrape_interval":"5s","static_configs":[{"targets":["bd-ops-opssight-core:3001","bd-ops-opssight-scanner:3003","bd-ops-opssight-image-getter:3004","bd-ops-opssight-pod-processor:3002"]}]}]}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: prometheus
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-prometheus
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: opssight
    component: prometheus
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-prometheus
    port: 3006
    protocol: TCP
    targetPort: 3006
  selector:
    app: opssight
    component: prometheus
    name: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
