apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: bd-ops
  name: bd-ops-opssight-image-processor
  namespace: bd-ops
spec:
  replicas: 1
  selector:
    app: opssight
    component: image-processor
    name: bd-ops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: image-processor
        name: bd-ops
      name: bd-ops-opssight-image-processor
    spec:
      containers:
      - args:
        - /etc/image-processor/opssight.json
        command:
        - ./opssight-image-processor
        image: docker.io/gautambaghel/opssight-image-processor:2.2.5
        name: image-processor
        ports:
        - containerPort: 3002
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 1300Mi
        volumeMounts:
        - mountPath: /etc/image-processor
          name: image-processor
        - mountPath: /tmp
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: PULL_SECRET_NAME
      serviceAccountName: bd-ops-opssight-processor
      volumes:
      - configMap:
          defaultMode: 420
          name: bd-ops-opssight-opssight
        name: image-processor
      - emptyDir: {}
        name: logs
status:
  replicas: 0
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: bd-ops
  name: bd-ops-opssight-image-processor
  namespace: bd-ops
spec:
  ports:
  - name: port-image-processor
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: opssight
    component: image-processor
    name: bd-ops
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: bd-ops
  name: bd-ops-opssight-image-processor
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: bd-ops-opssight-image-processor
subjects:
- kind: ServiceAccount
  name: bd-ops-opssight-processor
  namespace: bd-ops
