apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-image-processor
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
    {{- if .Values.enableImageProcessor }}
  replicas: 1
    {{- else }}
  replicas: 0
    {{- end }}
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    app: opssight
    component: image-processor
    name: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: image-processor
        name: {{ .Release.Name }}
      name: {{ .Release.Name }}-opssight-image-processor
    spec:
      containers:
      - args:
        - /etc/image-processor/opssight.json
        command:
        - ./opssight-image-processor
        {{- if .Values.imageProcessor.registry }}
          {{- if .Values.imageProcessor.imageTag }}
        image: {{ .Values.imageProcessor.registry }}/opssight-image-processor:{{ .Values.imageProcessor.imageTag }}
          {{- else }}
        image: {{ .Values.imageProcessor.registry }}/opssight-image-processor:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.imageProcessor.imageTag }}
        image: {{ .Values.registry }}/opssight-image-processor:{{ .Values.imageProcessor.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/opssight-image-processor:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        name: image-processor
        ports:
        - containerPort: 3002
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.imageProcessor.requestCpu }}
            memory: {{ .Values.imageProcessor.requestMemory }}
        volumeMounts:
        - mountPath: /etc/image-processor
          name: image-processor
        - mountPath: /tmp
          name: logs
      dnsPolicy: ClusterFirst
      {{- include "ops.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ .Release.Name }}-opssight-processor
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-opssight-opssight
        name: image-processor
      - emptyDir: {}
        name: logs
status:
  replicas: 0
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-image-processor
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-image-processor
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: opssight
    component: image-processor
    name: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: image-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-image-processor
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ .Release.Name }}-opssight-image-processor
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-opssight-processor
  namespace: {{ .Release.Namespace }}
