{{- if .Values.spec.perceiver.enableArtifactoryProcessor }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-artifactory-processor
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app: opssight
      component: artifactory-processor
      name: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: artifactory-processor
        name: {{ .Release.Name }}
      name: {{ .Release.Name }}-opssight-artifactory-processor
    spec:
      containers:
      - args:
        - /etc/artifactory-processor/opssight.json
        command:
        - ./opssight-artifactory-processor
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-opssight-blackduck
        {{- if .Values.artifactoryProcessor.registry }}
          {{- if .Values.artifactoryProcessor.imageTag }}
        image: {{ .Values.artifactoryProcessor.registry }}/opssight-artifactory-processor:{{ .Values.artifactoryProcessor.imageTag }}
          {{- else }}
        image: {{ .Values.artifactoryProcessor.registry }}/opssight-artifactory-processor:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.artifactoryProcessor.imageTag }}
        image: {{ .Values.registry }}/opssight-artifactory-processor:{{ .Values.artifactoryProcessor.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/opssight-artifactory-processor:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        name: artifactory-processor
        ports:
        - containerPort: {{ .Values.spec.perceiver.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.artifactoryProcessor.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/artifactory-processor
          name: artifactory-processor
        - mountPath: /tmp
          name: logs
      dnsPolicy: ClusterFirst
      {{- include "ops.imagePullSecrets" . | nindent 6 }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-opssight-opssight
        name: artifactory-processor
      - emptyDir: {}
        name: logs
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-artifactory-processor
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-artifactory-processor
    port: {{ .Values.spec.perceiver.port }}
    protocol: TCP
    targetPort: {{ .Values.spec.perceiver.port }}
  selector:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
---
{{- if or (eq .Values.spec.perceiver.exposeArtifactoryProcessor "NodePort") (eq .Values.spec.perceiver.exposeArtifactoryProcessor "LoadBalancer") }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opssight-artifactory-exposed
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-artifactory-exposed
    port: {{ .Values.spec.perceiver.port }}
    protocol: TCP
    targetPort: {{ .Values.spec.perceiver.port }}
  selector:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  type: {{ .Values.spec.perceiver.exposeArtifactoryProcessor }}
status:
  loadBalancer: {}
{{ else if eq .Values.spec.perceiver.exposeArtifactoryProcessor "OpenShift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-opssight-artifactory-exposed
  namespace: {{ .Release.Namespace }}
  labels:
    app: opssight
    component: artifactory-processor
    name: {{ .Release.Name }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  subdomain: ''
  to:
    kind: Service
    name: {{ .Release.Name }}-opssight-artifactory-processor
    weight: 100
  port:
    targetPort: port-artifactory-processor
  wildcardPolicy: None
{{ else }}
{{ end }}
{{- end }}
