apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: pod-processor
    name: bd-ops
  name: bd-ops-opssight-pod-processor
  namespace: bd-ops
spec:
  replicas: 1
  selector:
    app: opssight
    component: pod-processor
    name: bd-ops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        component: pod-processor
        name: bd-ops
      name: bd-ops-opssight-pod-processor
    spec:
      containers:
      - args:
        - /etc/pod-processor/opssight.json
        command:
        - ./opssight-pod-processor
        image: docker.io/blackducksoftware/opssight-pod-processor:2.2.5
        name: pod-processor
        ports:
        - containerPort: 3002
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 1300Mi
        volumeMounts:
        - mountPath: /etc/pod-processor
          name: pod-processor
        - mountPath: /tmp
          name: logs
      dnsPolicy: ClusterFirst
      serviceAccountName: bd-ops-opssight-processor
      volumes:
      - configMap:
          defaultMode: 420
          name: bd-ops-opssight-opssight
        name: pod-processor
      - emptyDir: {}
        name: logs
status:
  replicas: 0
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: pod-processor
    name: bd-ops
  name: bd-ops-opssight-pod-processor
  namespace: bd-ops
spec:
  ports:
  - name: port-pod-processor
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: opssight
    component: pod-processor
    name: bd-ops
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: processor
    name: bd-ops
  name: bd-ops-opssight-processor
  namespace: bd-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: pod-processor
    name: bd-ops
  name: bd-ops-opssight-pod-processor
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: bd-ops-opssight-pod-processor
subjects:
- kind: ServiceAccount
  name: bd-ops-opssight-processor
  namespace: bd-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: pod-processor
    name: bd-ops
  name: bd-ops-opssight-pod-processor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - update
