apiVersion: v1
data:
  blackduck.json: e30=
  securedRegistries.json: e30=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: opssight
    component: blackduck
    name: bd-ops
  name: bd-ops-opssight-blackduck
  namespace: bd-ops
type: Opaque
