apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jobrunners
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobrunner
  minReplicas: 1
  maxReplicas: 10
  # Increasing the number will slow the rate of scaling.
  targetCPUUtilizationPercentage: 20
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hub-scan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hub0scan
  minReplicas: 1
  maxReplicas: 10
  # Increasing the number will slow the rate of scaling.
  targetCPUUtilizationPercentage: 20
