.TH NAME
.PP
blackduck-operator


.SH DESCRIPTION
.PP
The blackduck-operator is used to deploy the Black Duck Operators.


.SH USAGE
.PP
The blackduck-operator will not perform meaningful work if launched outside of an OpenShift or Kubernetes environment or in a standalone fashion.


.PP
Please visit
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about OpsSight for Red Hat OpenShift.


.SH SECURITY IMPLICATIONS
.PP
Admin privileges are required to add roles to the service account. For more information, see the OpsSight for Red Hat OpenShift Security Disclosures document.

.SH AUTHORS
.PP
Black Duck Software
